"""Journey: Returning User Cook Flow.

Each virtual user represents one returning user who logs in (via a pre-seeded
token), browses the catalogue, picks a recipe, opens it, starts cook mode,
finishes cooking (updates pantry), and leaves a review. Then the next VU
starts another such journey from scratch.

Compared to the flat Scenario A/B/C harnesses, this is a *sequential*
state-carrying flow: each step depends on the result of the previous one,
mirroring how a real human moves through the app. That tests not just per-
endpoint throughput but the realistic cumulative cost of a user session.

Requires:
  - A seeded `fixtures/tokens.json` (generated by the backend's
    `seed_load_test_users` command, scp'd here).
  - The backend running with `LOAD_TEST_MODE=true` if you want push
    notifications, LLM, and other external clients mocked. Read-only steps
    in this journey don't fire externals; the cook-mode + review writes
    may dispatch FCM/notification tasks that DO need the mocks if you don't
    want real pushes.
"""

import random
import time

from locust import SequentialTaskSet, between, tag, task

from common import AuthenticatedHttpUser


@tag("journey", "cook")
class CookRecipeTasks(SequentialTaskSet):
    """The ordered flow each VU executes once, then loops back to step 1
    for the next iteration of this same user."""

    def on_start(self):
        # Per-journey state cleared each loop
        self.recipe_uuid = None
        self.cart_id = None

    # --- step 1: land on the catalogue ------------------------------------

    @task
    def open_app(self):
        """First request a user makes after launching the app."""
        with self.client.get(
            "/recipes/list/?page=1",
            name="01 GET /recipes/list/ (landing)",
            catch_response=True,
        ) as r:
            if r.status_code != 200:
                r.failure(f"landing list returned {r.status_code}")
                self.interrupt()
                return
            try:
                results = r.json().get("results") or []
            except ValueError:
                r.failure("landing list response not JSON")
                self.interrupt()
                return
            if not results:
                r.failure("landing list empty")
                self.interrupt()
                return
            self.recipe_uuid = random.choice(results).get("id")
            if not self.recipe_uuid:
                r.failure("first list item has no id")
                self.interrupt()

    # --- step 2: open the chosen recipe ----------------------------------

    @task
    def open_detail(self):
        if not self.recipe_uuid:
            self.interrupt()
            return
        self.client.get(
            f"/recipes/{self.recipe_uuid}/",
            name="02 GET /recipes/[uuid]/ (detail)",
        )

    # --- step 3: peek at the reviews -------------------------------------

    @task
    def peek_reviews(self):
        self.client.get(
            f"/recipes/{self.recipe_uuid}/reviews/",
            name="03 GET /recipes/[uuid]/reviews/",
        )

    # --- step 4: check products needed -----------------------------------

    @task
    def view_products(self):
        with self.client.get(
            f"/recipes/{self.recipe_uuid}/products/",
            name="04 GET /recipes/[uuid]/products/",
            catch_response=True,
        ) as r:
            # 400 here is the documented "no approved product for ingredient X"
            # case — the user picked a recipe with an unmapped ingredient. The
            # journey continues (real user would pick a different recipe).
            if r.status_code == 400:
                r.success()

    # --- step 5: enter cook mode -----------------------------------------

    @task
    def start_cook(self):
        self.client.post(
            f"/recipes/{self.recipe_uuid}/cook-mode/start/",
            json={"products": [], "serving_size": random.choice([1, 2, 4])},
            name="05 POST /recipes/[uuid]/cook-mode/start/",
        )

    # --- step 6: finish cooking, update pantry ---------------------------

    @task
    def update_pantry_after_cook(self):
        self.client.post(
            f"/recipes/{self.recipe_uuid}/cook-mode/update-pantry/",
            json={"updates": []},
            name="06 POST /recipes/[uuid]/cook-mode/update-pantry/",
        )

    # --- step 7: leave a review ------------------------------------------

    @task
    def submit_review(self):
        self.client.post(
            f"/recipes/{self.recipe_uuid}/reviews/",
            json={
                "stars": random.randint(3, 5),
                "comment": random.choice(
                    [
                        "Loved it!",
                        "Quick and easy.",
                        "Will make again.",
                        "Family approved.",
                    ],
                ),
            },
            name="07 POST /recipes/[uuid]/reviews/",
        )

    # --- step 8: loop / leave --------------------------------------------

    @task
    def loop_or_leave(self):
        """Realistic users either browse more or close the app. 70% loop."""
        if random.random() < 0.7:
            # Restart the journey from step 1 for the same VU
            time.sleep(random.uniform(2.0, 8.0))
            self.interrupt(reschedule=True)
        else:
            self.interrupt(reschedule=False)


class ReturningUserCookUser(AuthenticatedHttpUser):
    """One VU = one returning user living through repeated cook journeys.

    `between(1.0, 5.0)` simulates think-time between steps inside one journey.
    """

    wait_time = between(1.0, 5.0)
    tasks = [CookRecipeTasks]
